### ISSUE TITLE
Does it support files too?

### ISSUE THREAD

**Issue by 0xRampey** [dcervenkov/ulauncher-z-search#1]

**Comment by dcervenkov** [comment]
The `z` utility works on directories only - it works in tandem with the `cd` command, automatically populating the `z` list with directories visited using `cd`.

So the short answer is no. However, I also feel the need for a fast file search and have some ideas. I plan to make a new plugin for that when I have more free time.

In the meantime, give [this one](https://ext.ulauncher.io/-/github-brpaz-ulauncher-file-search) a try. It's not as fast as I'd like but otherwise works well.
